server:
  port: ${port:8010}
  shutdown: graceful

spring:
  application:
    name: split-and-pay-backend-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/split-and-pay
      auto-index-creation: true

proverka.cheka.token: 24687.nXWbO7tBku60RwVnm

logging:
  file:
    name: ${log.dir:/tmp}/split-and-pay-backend-service.main.log
  level:
    org.springframework: trace
